// src/jobs/telemetryPoller.js
// ─────────────────────────────────────────────────────────────────────────────
// Background cron job that polls smart plugs every 30 seconds.
// For simulated plugs, readings are generated by SmartPlugSimulatorService.
// For real plugs, SmartPlugSimulatorService.readPlug() is the swap point
// (see production comments inside that service).
//
// Flow per tick:
//   1. Fetch all active smart plugs from MongoDB
//   2. For each plug, read wattage (simulator or real vendor)
//   3. Run AnomalyDetectionService → persists reading + fires alert if needed
//   4. Handle errors per-plug without crashing the overall job
// ─────────────────────────────────────────────────────────────────────────────

const cron              = require('node-cron');
const SmartPlug         = require('../models/SmartPlug.model');
const Appliance         = require('../models/Appliance.model');
const { readPlug }      = require('../services/SmartPlugSimulatorService');
const { analyseReading } = require('../services/AnomalyDetectionService');

// How many plugs to process in parallel per tick (prevents memory spikes)
const CONCURRENCY = 10;

// Track if a tick is already running to prevent overlap
let _running = false;

/**
 * Process a single plug within a cron tick.
 */
async function _processSinglePlug(plug) {
  try {
    // Resolve linked appliance for accurate wattage profile
    const appliance = plug.applianceId
      ? await Appliance.findById(plug.applianceId).lean()
      : null;

    // Read current wattage (swap readPlug() for real vendor call in production)
    const measurement = readPlug(plug, appliance);

    // Analyse for anomalies and persist reading
    await analyseReading({ plug, appliance, ...measurement });
  } catch (err) {
    // Per-plug error: log but continue processing other plugs
    console.error(`[TelemetryPoller] Error processing plug ${plug.plugId}:`, err.message);
  }
}

/**
 * Execute one full polling cycle across all active plugs.
 */
async function _pollTick() {
  if (_running) {
    console.warn('[TelemetryPoller] Previous tick still running — skipping this cycle.');
    return;
  }
  _running = true;

  try {
    // Fetch all active plugs (both simulated and real)
    const plugs = await SmartPlug.find({ isActive: true }).lean();

    if (plugs.length === 0) {
      _running = false;
      return;
    }

    // Process in batches of CONCURRENCY
    for (let i = 0; i < plugs.length; i += CONCURRENCY) {
      const batch = plugs.slice(i, i + CONCURRENCY);
      await Promise.all(batch.map(_processSinglePlug));
    }

    console.log(`[TelemetryPoller] ✓ Processed ${plugs.length} plug(s) at ${new Date().toISOString()}`);
  } catch (err) {
    console.error('[TelemetryPoller] Fatal tick error:', err.message);
  } finally {
    _running = false;
  }
}

/**
 * Start the background telemetry polling scheduler.
 * Call this once after the database connection is established.
 */
function startTelemetryPoller() {
  // Run every 30 seconds: "*/30 * * * * *" (6-part cron with seconds)
  cron.schedule('*/30 * * * * *', _pollTick, {
    scheduled: true,
    timezone:  'Asia/Kolkata',
  });

  console.log('[TelemetryPoller] 🔌 Smart plug telemetry poller started (every 30s)');
}

module.exports = { startTelemetryPoller };
