// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgQqr4yXRTOun731QFbb7L3REML9s7BVg',
    appId: '1:368122766341:web:5bd25d96afec423840e86c',
    messagingSenderId: '368122766341',
    projectId: 'team-synapse-34703',
    authDomain: 'team-synapse-34703.firebaseapp.com',
    storageBucket: 'team-synapse-34703.firebasestorage.app',
    measurementId: 'G-0MPH1365PV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_eWZ_KqhgFfnmTXxZJt_fx9MTLtGjwHs',
    appId: '1:368122766341:android:963d9316cabdb9c040e86c',
    messagingSenderId: '368122766341',
    projectId: 'team-synapse-34703',
    storageBucket: 'team-synapse-34703.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBldRH8psCkwluFcb_UL7BmmyXKycORJ8I',
    appId: '1:368122766341:ios:57942d262a32f3df40e86c',
    messagingSenderId: '368122766341',
    projectId: 'team-synapse-34703',
    storageBucket: 'team-synapse-34703.firebasestorage.app',
    iosBundleId: 'com.example.wattSense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBldRH8psCkwluFcb_UL7BmmyXKycORJ8I',
    appId: '1:368122766341:ios:57942d262a32f3df40e86c',
    messagingSenderId: '368122766341',
    projectId: 'team-synapse-34703',
    storageBucket: 'team-synapse-34703.firebasestorage.app',
    iosBundleId: 'com.example.wattSense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgQqr4yXRTOun731QFbb7L3REML9s7BVg',
    appId: '1:368122766341:web:beac983e01d0717540e86c',
    messagingSenderId: '368122766341',
    projectId: 'team-synapse-34703',
    authDomain: 'team-synapse-34703.firebaseapp.com',
    storageBucket: 'team-synapse-34703.firebasestorage.app',
    measurementId: 'G-KKPKYEVQ24',
  );
}
